version: '3'

vars:
  FIND_POSTGRES: $(docker ps | grep -i postgres:latest | awk '{print $1}')
  POSTGRES_URL: postgres://daniluk_admin:mimimidi1@localhost:5436/pastebin_backend?sslmode=disable

tasks:

  run-migrations:
    cmds:
      - migrate -path migrations/ -database {{.POSTGRES_URL}} up
  dev-up:
    cmds:
      - docker compose -f infra/postgres.yaml up -d
      - docker compose -f infra/minio.yaml up -d
  run-tests:
    cmds:
      - docker run -d -p 5437:5432 -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test -e POSTGRES_DB=test --name test_postgr postgres:16
      - docker inspect --format '{{ .NetworkSettings.IPAddress }}:5437' test_postgr | xargs wget --retry-connrefused --tries=5 -q --wait=3 --spider
      - export TEST_DB_URL='postgres://test:test@localhost:5437/test?sslmode=disable'
      - go test ./...
      - docker stop test_postgr
  
  dev-postgres-attach:
    cmds:
      - echo {{.FIND_POSTGRES}}
      - docker attach {{.FIND_POSTGRES}}
  
  dev-postgres-connect:
    cmds:
      - docker exec -it {{.FIND_POSTGRES}} psql -U daniluk_admin pastebin_backend

  dev-rm-volumes:
    cmds:
      - docker volume rm $(docker volume ls | grep -i infra)