BEGIN;


CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE tokens(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id INTEGER REFERENCES users(id) NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);

COMMIT;