// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hashed) VALUES ($1, $2, $3) RETURNING id
`

type CreateUserParams struct {
	Name           string
	Email          string
	PasswordHashed string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHashed)
	var id int32
	err := row.Scan(&id)
	return id, err
}
