env: dev

jwt:
  access_token_ttl: 60m
  refresh_token_ttl: 168h
  signing_key: HxElqFg0/pr@3cVO*sAdMt@n

http:
  port: 8080
  write_timeout: 10s
  read_timeout: 10s

postgres:
  username: daniluk_admin
  password: mimimidi1
  host: past_postgr
  port: 5432
  db_name: pastebin_backend
  ssl_mode: disable

minio:
  endpoint: minio-server:9000
  access_key: BPYUnB5lsb2sR8OKZYcL
  secret_key: iKScGSBikEX4H4EBfX7PacXTaXfUA7hOmenpVm0S
  use_secure: false
