env: dev

http:
  port: 8080
  write_timeout: 10s
  read_timeout: 10s

postgres:
  username: daniluk_admin
  password: mimimidi1
  host: localhost
  port: 5436
  db_name: pastebin_backend
  ssl_mode: disable
