on: [push]

jobs:
  my_build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: hello world
        run: echo "Hello, world!"

      - name: multiple line script
        run: |
          echo "This project requires strong go knowledges"
          echo "Also reqieres strong backend knowledges"
      - name: setup go
        uses: actions/setup-go@v5
      - run: "echo ${{ job.status }}"
      
